apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oscasme-juiceshop
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/oscasme2380/cicd-demo.git'
    path: app
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: oscasme
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
